require 'json'
require 'pathname'

# Resolve react_native_pods.rb with node to allow for hoisting
react_native_pods_path = Pod::Executable.execute_command('node', ['-p', <<-JS
  require.resolve(
    'react-native/scripts/react_native_pods.rb',
    { paths: [process.argv[1]] }
  )
JS
, __dir__]).strip

require react_native_pods_path

platform :ios, '11.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AndroidSinchExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AndroidSinchExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end